version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    working_directory: ~/demorepo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv 
            . venv/bin/activate
            make install 
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make lint
workflows:
  sample: 
    jobs:
      - build-and-test
